const Cards = [
  {
    title: 'TheThing',
    imagePath: '/images/TheThing.png',
    count: {
      4: 1,
      5: 1,
      6: 1,
      7: 1,
      8: 1,
      9: 1,
      10: 1,
      11: 1,
    },
    imageBackside: '/images/event.png',
    alt: 'TheThing',
    on: [],
    action: 'TheThing',
    type: 'notpanic',
    description: {},
  },
  {
    title: 'Infected',
    imagePath: '/images/Infected1.png',
    count: {
      4: 8,
      5: 8,
      6: 9,
      7: 12,
      8: 13,
      9: 15,
      10: 17,
      11: 20,
    },
    imageBackside: '/images/event.png',
    alt: 'Infected',
    on: [],
    action: 'Infected',
    type: 'notpanic',
    description: {},
  },
  {
    title: 'FlameThrower',
    imagePath: '/images/FlameThrower.png',
    count: {
      4: 2,
      5: 2,
      6: 3,
      7: 3,
      8: 3,
      9: 4,
      10: 4,
      11: 5,
    },
    imageBackside: '/images/event.png',
    alt: 'FlameThrower',
    on: [],
    action: 'FlameThrower',
    type: 'notpanic',
    description: {},
  },
  {
    title: 'Analysis',
    imagePath: '/images/Analysis.png',
    count: {
      4: 0,
      5: 1,
      6: 2,
      7: 2,
      8: 2,
      9: 3,
      10: 3,
      11: 3,
    },
    imageBackside: '/images/event.png',
    alt: 'Analysis',
    on: [],
    action: 'Analysis',
    type: 'notpanic',
    description: {},
  },
  {
    title: 'Axe',
    imagePath: '/images/Axe.png',
    count: {
      4: 1,
      5: 1,
      6: 1,
      7: 1,
      8: 1,
      9: 2,
      10: 2,
      11: 2,
    },
    imageBackside: '/images/event.png',
    alt: 'Axe',
    on: [],
    action: 'Axe',
    type: 'notpanic',
    description: {},
  },
  {
    title: 'Suspicious',
    imagePath: '/images/Suspicious.png',
    count: {
      4: 4,
      5: 4,
      6: 4,
      7: 5,
      8: 6,
      9: 7,
      10: 8,
      11: 8,
    },
    imageBackside: '/images/event.png',
    alt: 'Suspicious',
    on: [],
    action: 'Suspicious',
    type: 'notpanic',
    description: {},
  },
  {
    title: 'Whiskey',
    imagePath: '/images/Whiskey.png',
    count: {
      4: 1,
      5: 1,
      6: 2,
      7: 2,
      8: 2,
      9: 2,
      10: 3,
      11: 3,
    },
    imageBackside: '/images/event.png',
    alt: 'Whiskey',
    on: [],
    action: 'Whiskey',
    type: 'notpanic',
    description: {},
  },
  {
    title: 'Resolute',
    imagePath: '/images/Resolute.png',
    count: {
      4: 2,
      5: 2,
      6: 3,
      7: 3,
      8: 3,
      9: 4,
      10: 4,
      11: 4,
    },
    imageBackside: '/images/event.png',
    alt: 'Resolute',
    on: [],
    action: 'Resolute',
    type: 'notpanic',
    description: {},
  },
  {
    title: 'WatchYourBack',
    imagePath: '/images/WatchYourBack.png',
    count: {
      4: 1,
      5: 1,
      6: 1,
      7: 1,
      8: 1,
      9: 2,
      10: 2,
      11: 2,
    },
    imageBackside: '/images/event.png',
    alt: 'WatchYourBack',
    on: [],
    action: 'WatchYourBack',
    type: 'notpanic',
    description: {},
  },
  {
    title: 'ChangePlaces',
    imagePath: '/images/ChangePlaces.png',
    count: {
      4: 2,
      5: 2,
      6: 2,
      7: 3,
      8: 4,
      9: 5,
      10: 5,
      11: 6,
    },
    imageBackside: '/images/event.png',
    alt: 'ChangePlaces',
    on: [],
    action: 'ChangePlaces',
    type: 'notpanic',
    description: {},
  },
  {
    title: 'YoudBetterRun',
    imagePath: '/images/YoudBetterRun.png',
    count: {
      4: 2,
      5: 2,
      6: 2,
      7: 3,
      8: 3,
      9: 4,
      10: 4,
      11: 5,
    },
    imageBackside: '/images/event.png',
    alt: 'YoudBetterRun',
    on: [],
    action: 'YoudBetterRun',
    type: 'notpanic',
    description: {},
  },
  {
    title: 'Seduction',
    imagePath: '/images/Seduction.png',
    count: {
      4: 2,
      5: 2,
      6: 3,
      7: 4,
      8: 5,
      9: 5,
      10: 6,
      11: 7,
    },
    imageBackside: '/images/event.png',
    alt: 'Seduction',
    on: [],
    action: 'Seduction',
    type: 'notpanic',
    description: {},
  },
  {
    title: 'Scary',
    imagePath: '/images/Scary.png',
    count: {
      4: 0,
      5: 1,
      6: 2,
      7: 2,
      8: 3,
      9: 3,
      10: 3,
      11: 4,
    },
    imageBackside: '/images/event.png',
    alt: 'Scary',
    on: [],
    action: 'Scary',
    type: 'notpanic',
    description: {},
  },
  {
    title: 'ImComfortable',
    imagePath: '/images/ImComfortable.png',
    count: {
      4: 1,
      5: 1,
      6: 2,
      7: 2,
      8: 2,
      9: 2,
      10: 2,
      11: 3,
    },
    imageBackside: '/images/event.png',
    alt: 'ImComfortable',
    on: [],
    action: 'ImComfortable',
    type: 'notpanic',
    description: {},
  },
  {
    title: 'NoThanks',
    imagePath: '/images/NoThanks.png',
    count: {
      4: 1,
      5: 1,
      6: 2,
      7: 2,
      8: 3,
      9: 3,
      10: 3,
      11: 4,
    },
    imageBackside: '/images/event.png',
    alt: 'NoThanks',
    on: [],
    action: 'NoThanks',
    type: 'notpanic',
    description: {},
  },
  {
    title: 'Missed',
    imagePath: '/images/Missed.png',
    count: {
      4: 1,
      5: 1,
      6: 2,
      7: 2,
      8: 2,
      9: 2,
      10: 2,
      11: 3,
    },
    imageBackside: '/images/event.png',
    alt: 'Missed',
    on: [],
    action: 'Missed',
    type: 'notpanic',
    description: {},
  },
  {
    title: 'NoBarbecue',
    imagePath: '/images/NoBarbecue.png',
    count: {
      4: 1,
      5: 1,
      6: 2,
      7: 2,
      8: 2,
      9: 2,
      10: 2,
      11: 3,
    },
    imageBackside: '/images/event.png',
    alt: 'NoBarbecue',
    on: [],
    action: 'NoBarbecue',
    type: 'notpanic',
    description: {},
  },
  {
    title: 'Quarantine',
    imagePath: '/images/Quarantine.png',
    count: {
      4: 0,
      5: 1,
      6: 1,
      7: 1,
      8: 1,
      9: 2,
      10: 2,
      11: 2,
    },
    imageBackside: '/images/event.png',
    alt: 'Quarantine',
    on: [],
    action: 'Quarantine',
    type: 'notpanic',
    description: {},
  },
  {
    title: 'BarredDoor',
    imagePath: '/images/BarredDoor.png',
    count: {
      4: 1,
      5: 1,
      6: 1,
      7: 2,
      8: 2,
      9: 2,
      10: 2,
      11: 3,
    },
    imageBackside: '/images/event.png',
    alt: 'BarredDoor',
    on: [],
    action: 'BarredDoor',
    type: 'notpanic',
    description: {},
  },
  {
    title: 'RottenRopes',
    imagePath: '/images/RottenRopes.png',
    count: {
      4: 0,
      5: 0,
      6: 1,
      7: 1,
      8: 1,
      9: 2,
      10: 2,
      11: 2,
    },
    imageBackside: '/images/panic.png',
    alt: 'RottenRopes',
    on: [],
    action: 'RottenRopes',
    type: 'panic',
    description: {},
  },
  {
    title: 'Revelations',
    imagePath: '/images/Revelations.png',
    count: {
      4: 0,
      5: 0,
      6: 0,
      7: 0,
      8: 1,
      9: 1,
      10: 1,
      11: 1,
    },
    imageBackside: '/images/panic.png',
    alt: 'Revelations',
    on: [],
    action: 'Revelations',
    type: 'panic',
    description: {},
  },
  {
    title: 'OneTwo',
    imagePath: '/images/OneTwo.png',
    count: {
      4: 0,
      5: 1,
      6: 1,
      7: 1,
      8: 1,
      9: 2,
      10: 2,
      11: 2,
    },
    imageBackside: '/images/panic.png',
    alt: 'OneTwo',
    on: [],
    action: 'OneTwo',
    type: 'panic',
    description: {},
  },
  {
    title: 'ThreeFour',
    imagePath: '/images/ThreeFour.png',
    count: {
      4: 1,
      5: 1,
      6: 1,
      7: 1,
      8: 1,
      9: 2,
      10: 2,
      11: 2,
    },
    imageBackside: '/images/panic.png',
    alt: 'ThreeFour',
    on: [],
    action: 'ThreeFour',
    type: 'panic',
    description: {},
  },
  {
    title: 'SoThisIstheParty',
    imagePath: '/images/SoThisIstheParty.png',
    count: {
      4: 0,
      5: 1,
      6: 1,
      7: 1,
      8: 1,
      9: 2,
      10: 2,
      11: 2,
    },
    imageBackside: '/images/panic.png',
    alt: 'SoThisIstheParty',
    on: [],
    action: 'SoThisIstheParty',
    type: 'panic',
    description: {},
  },
  {
    title: 'GoAway',
    imagePath: '/images/GoAway.png',
    count: {
      4: 0,
      5: 1,
      6: 1,
      7: 1,
      8: 1,
      9: 1,
      10: 1,
      11: 1,
    },
    imageBackside: '/images/panic.png',
    alt: 'GoAway',
    on: [],
    action: 'GoAway',
    type: 'panic',
    description: {},
  },
  {
    title: 'Forgetfull',
    imagePath: '/images/Forgetfull.png',
    count: {
      4: 1,
      5: 1,
      6: 1,
      7: 1,
      8: 1,
      9: 1,
      10: 1,
      11: 1,
    },
    imageBackside: '/images/panic.png',
    alt: 'Forgetfull',
    on: [],
    action: 'Forgetfull',
    type: 'panic',
    description: {},
  },
  {
    title: 'RoundandRound',
    imagePath: '/images/RoundandRound.png',
    count: {
      4: 1,
      5: 1,
      6: 1,
      7: 1,
      8: 1,
      9: 2,
      10: 2,
      11: 2,
    },
    imageBackside: '/images/panic.png',
    alt: 'RoundandRound',
    on: [],
    action: 'RoundandRound',
    type: 'panic',
    description: {},
  },
  {
    title: 'BeFriends',
    imagePath: '/images/BeFriends.png',
    count: {
      4: 0,
      5: 0,
      6: 0,
      7: 1,
      8: 1,
      9: 2,
      10: 2,
      11: 2,
    },
    imageBackside: '/images/panic.png',
    alt: 'BeFriends',
    on: [],
    action: 'BeFriends',
    type: 'panic',
    description: {},
  },
  {
    title: 'BlindDate',
    imagePath: '/images/BlindDate.png',
    count: {
      4: 1,
      5: 1,
      6: 1,
      7: 1,
      8: 1,
      9: 2,
      10: 2,
      11: 2,
    },
    imageBackside: '/images/panic.png',
    alt: 'BlindDate',
    on: [],
    action: 'BlindDate',
    type: 'panic',
    description: {},
  },
  {
    title: 'Ooops',
    imagePath: '/images/Ooops.png',
    count: {
      4: 0,
      5: 0,
      6: 0,
      7: 0,
      8: 0,
      9: 0,
      10: 1,
      11: 1,
    },
    imageBackside: '/images/panic.png',
    alt: 'Ooops',
    on: [],
    action: 'Ooops',
    type: 'panic',
    description: {},
  },
  {
    title: 'BetweenUs',
    imagePath: '/images/BetweenUs.png',
    count: {
      4: 0,
      5: 0,
      6: 0,
      7: 1,
      8: 1,
      9: 2,
      10: 2,
      11: 2,
    },
    imageBackside: '/images/panic.png',
    alt: 'BetweenUs',
    on: [],
    action: 'BetweenUs',
    type: 'panic',
    description: {},
  },
]

function initializeDeck(num) {
  const deck = []
  Cards.forEach((c) => {
    for (let i = 0; i < c.count[num]; i++) {
      deck.push({
        id: 0,
        title: c.title,
        imagePath: c.imagePath,
        imageBackside: c.imageBackside,
        alt: c.alt,
        on: c.on,
        action: c.action,
        type: c.type,
        description: c.description,
      })
    }
  })
  return deck.map((c, idx) => ({ ...c, id: idx }))
}
function shuffleDeck(deck) {
  for (var i = deck.length - 1; i > 0; i--) {
    var j = Math.floor(Math.random() * (i + 1))
    var temp = deck[i]
    deck[i] = deck[j]
    deck[j] = temp
  }
  return deck
}
export { initializeDeck, shuffleDeck }
