const Cards = [
  {
    title: 'TheThing',
    imagePath: '/images/TheThing.png',
    count: {
      4: 1,
      5: 1,
      6: 1,
      7: 1,
      8: 1,
      9: 1,
      10: 1,
      11: 1,
    },
    imageBackside: '/images/event.png',
    alt: 'TheThing',
    on: [],
    action: 'TheThing',
    type: 'notpanic',
    description: {},
  },
  {
    title: 'Infected',
    imagePath: '/images/Infected1.png',
    count: {
      4: 1,
      5: 1,
      6: 1,
      7: 1,
      8: 1,
      9: 1,
      10: 1,
      11: 1,
    },
    imageBackside: '/images/event.png',
    alt: 'Infected',
    on: [],
    action: 'Infected',
    type: 'notpanic',
    description: {},
  },
  {
    title: 'FlameThrower',
    imagePath: '/images/FlameThrower.png',
    count: {
      4: 1,
      5: 1,
      6: 1,
      7: 1,
      8: 1,
      9: 1,
      10: 1,
      11: 1,
    },
    imageBackside: '/images/event.png',
    alt: 'FlameThrower',
    on: [],
    action: 'FlameThrower',
    type: 'notpanic',
    description: {},
  },
  {
    title: 'Analysis',
    imagePath: '/images/Analysis.png',
    count: {
      4: 1,
      5: 1,
      6: 1,
      7: 1,
      8: 1,
      9: 1,
      10: 1,
      11: 1,
    },
    imageBackside: '/images/event.png',
    alt: 'Analysis',
    on: [],
    action: 'Analysis',
    type: 'notpanic',
    description: {},
  },
  {
    title: 'Axe',
    imagePath: '/images/Axe.png',
    count: {
      4: 1,
      5: 1,
      6: 1,
      7: 1,
      8: 1,
      9: 1,
      10: 1,
      11: 1,
    },
    imageBackside: '/images/event.png',
    alt: 'Axe',
    on: [],
    action: 'Axe',
    type: 'notpanic',
    description: {},
  },
  {
    title: 'Suspicious',
    imagePath: '/images/Suspicious.png',
    count: {
      4: 1,
      5: 1,
      6: 1,
      7: 1,
      8: 1,
      9: 1,
      10: 1,
      11: 1,
    },
    imageBackside: '/images/event.png',
    alt: 'Suspicious',
    on: [],
    action: 'Suspicious',
    type: 'notpanic',
    description: {},
  },
  {
    title: 'Whiskey',
    imagePath: '/images/Whiskey.png',
    count: {
      4: 1,
      5: 1,
      6: 1,
      7: 1,
      8: 1,
      9: 1,
      10: 1,
      11: 1,
    },
    imageBackside: '/images/event.png',
    alt: 'Whiskey',
    on: [],
    action: 'Whiskey',
    type: 'notpanic',
    description: {},
  },
  {
    title: 'Resolute',
    imagePath: '/images/Resolute.png',
    count: {
      4: 1,
      5: 1,
      6: 1,
      7: 1,
      8: 1,
      9: 1,
      10: 1,
      11: 1,
    },
    imageBackside: '/images/event.png',
    alt: 'Resolute',
    on: [],
    action: 'Resolute',
    type: 'notpanic',
    description: {},
  },
  {
    title: 'WatchYourBack',
    imagePath: '/images/WatchYourBack.png',
    count: {
      4: 1,
      5: 1,
      6: 1,
      7: 1,
      8: 1,
      9: 1,
      10: 1,
      11: 1,
    },
    imageBackside: '/images/event.png',
    alt: 'WatchYourBack',
    on: [],
    action: 'WatchYourBack',
    type: 'notpanic',
    description: {},
  },
  {
    title: 'ChangePlaces',
    imagePath: '/images/ChangePlaces.png',
    count: {
      4: 1,
      5: 1,
      6: 1,
      7: 1,
      8: 1,
      9: 1,
      10: 1,
      11: 1,
    },
    imageBackside: '/images/event.png',
    alt: 'ChangePlaces',
    on: [],
    action: 'ChangePlaces',
    type: 'notpanic',
    description: {},
  },
  {
    title: 'YoudBetterRun',
    imagePath: '/images/YoudBetterRun.png',
    count: {
      4: 1,
      5: 1,
      6: 1,
      7: 1,
      8: 1,
      9: 1,
      10: 1,
      11: 1,
    },
    imageBackside: '/images/event.png',
    alt: 'YoudBetterRun',
    on: [],
    action: 'YoudBetterRun',
    type: 'notpanic',
    description: {},
  },
  {
    title: 'Seduction',
    imagePath: '/images/Seduction.png',
    count: {
      4: 1,
      5: 1,
      6: 1,
      7: 1,
      8: 1,
      9: 1,
      10: 1,
      11: 1,
    },
    imageBackside: '/images/event.png',
    alt: 'Seduction',
    on: [],
    action: 'Seduction',
    type: 'notpanic',
    description: {},
  },
  {
    title: 'Scary',
    imagePath: '/images/Scary.png',
    count: {
      4: 1,
      5: 1,
      6: 1,
      7: 1,
      8: 1,
      9: 1,
      10: 1,
      11: 1,
    },
    imageBackside: '/images/event.png',
    alt: 'Scary',
    on: [],
    action: 'Scary',
    type: 'notpanic',
    description: {},
  },
  {
    title: 'ImComfortable',
    imagePath: '/images/ImComfortable.png',
    count: {
      4: 1,
      5: 1,
      6: 1,
      7: 1,
      8: 1,
      9: 1,
      10: 1,
      11: 1,
    },
    imageBackside: '/images/event.png',
    alt: 'ImComfortable',
    on: [],
    action: 'ImComfortable',
    type: 'notpanic',
    description: {},
  },
  {
    title: 'NoThanks',
    imagePath: '/images/NoThanks.png',
    count: {
      4: 1,
      5: 1,
      6: 1,
      7: 1,
      8: 1,
      9: 1,
      10: 1,
      11: 1,
    },
    imageBackside: '/images/event.png',
    alt: 'NoThanks',
    on: [],
    action: 'NoThanks',
    type: 'notpanic',
    description: {},
  },
  {
    title: 'Missed',
    imagePath: '/images/Missed.png',
    count: {
      4: 1,
      5: 1,
      6: 1,
      7: 1,
      8: 1,
      9: 1,
      10: 1,
      11: 1,
    },
    imageBackside: '/images/event.png',
    alt: 'Missed',
    on: [],
    action: 'Missed',
    type: 'notpanic',
    description: {},
  },
  {
    title: 'NoBarbecue',
    imagePath: '/images/NoBarbecue.png',
    count: {
      4: 1,
      5: 1,
      6: 1,
      7: 1,
      8: 1,
      9: 1,
      10: 1,
      11: 1,
    },
    imageBackside: '/images/event.png',
    alt: 'NoBarbecue',
    on: [],
    action: 'NoBarbecue',
    type: 'notpanic',
    description: {},
  },
  {
    title: 'Quarantine',
    imagePath: '/images/Quarantine.png',
    count: {
      4: 1,
      5: 1,
      6: 1,
      7: 1,
      8: 1,
      9: 1,
      10: 1,
      11: 1,
    },
    imageBackside: '/images/event.png',
    alt: 'Quarantine',
    on: [],
    action: 'Quarantine',
    type: 'notpanic',
    description: {},
  },
  {
    title: 'BarredDoor',
    imagePath: '/images/BarredDoor.png',
    count: {
      4: 1,
      5: 1,
      6: 1,
      7: 1,
      8: 1,
      9: 1,
      10: 1,
      11: 1,
    },
    imageBackside: '/images/event.png',
    alt: 'BarredDoor',
    on: [],
    action: 'BarredDoor',
    type: 'notpanic',
    description: {},
  },
  {
    title: 'RottenRopes',
    imagePath: '/images/RottenRopes.png',
    count: {
      4: 1,
      5: 1,
      6: 1,
      7: 1,
      8: 1,
      9: 1,
      10: 1,
      11: 1,
    },
    imageBackside: '/images/event.png',
    alt: 'RottenRopes',
    on: [],
    action: 'RottenRopes',
    type: 'notpanic',
    description: {},
  },
  {
    title: 'Revelations',
    imagePath: '/images/Revelations.png',
    count: {
      4: 1,
      5: 1,
      6: 1,
      7: 1,
      8: 1,
      9: 1,
      10: 1,
      11: 1,
    },
    imageBackside: '/images/event.png',
    alt: 'Revelations',
    on: [],
    action: 'Revelations',
    type: 'notpanic',
    description: {},
  },
  {
    title: 'OneTwo',
    imagePath: '/images/OneTwo.png',
    count: {
      4: 1,
      5: 1,
      6: 1,
      7: 1,
      8: 1,
      9: 1,
      10: 1,
      11: 1,
    },
    imageBackside: '/images/event.png',
    alt: 'OneTwo',
    on: [],
    action: 'OneTwo',
    type: 'notpanic',
    description: {},
  },
  {
    title: 'ThreeFour',
    imagePath: '/images/ThreeFour.png',
    count: {
      4: 1,
      5: 1,
      6: 1,
      7: 1,
      8: 1,
      9: 1,
      10: 1,
      11: 1,
    },
    imageBackside: '/images/event.png',
    alt: 'ThreeFour',
    on: [],
    action: 'ThreeFour',
    type: 'notpanic',
    description: {},
  },
  {
    title: 'SoThisIstheParty',
    imagePath: '/images/SoThisIstheParty.png',
    count: {
      4: 1,
      5: 1,
      6: 1,
      7: 1,
      8: 1,
      9: 1,
      10: 1,
      11: 1,
    },
    imageBackside: '/images/event.png',
    alt: 'SoThisIstheParty',
    on: [],
    action: 'SoThisIstheParty',
    type: 'notpanic',
    description: {},
  },
  {
    title: 'GoAway',
    imagePath: '/images/GoAway.png',
    count: {
      4: 1,
      5: 1,
      6: 1,
      7: 1,
      8: 1,
      9: 1,
      10: 1,
      11: 1,
    },
    imageBackside: '/images/event.png',
    alt: 'GoAway',
    on: [],
    action: 'GoAway',
    type: 'notpanic',
    description: {},
  },
  {
    title: 'Forgetfull',
    imagePath: '/images/Forgetfull.png',
    count: {
      4: 1,
      5: 1,
      6: 1,
      7: 1,
      8: 1,
      9: 1,
      10: 1,
      11: 1,
    },
    imageBackside: '/images/event.png',
    alt: 'Forgetfull',
    on: [],
    action: 'Forgetfull',
    type: 'notpanic',
    description: {},
  },
  {
    title: 'RoundandRound',
    imagePath: '/images/RoundandRound.png',
    count: {
      4: 1,
      5: 1,
      6: 1,
      7: 1,
      8: 1,
      9: 1,
      10: 1,
      11: 1,
    },
    imageBackside: '/images/event.png',
    alt: 'RoundandRound',
    on: [],
    action: 'RoundandRound',
    type: 'notpanic',
    description: {},
  },
  {
    title: 'BeFriends',
    imagePath: '/images/BeFriends.png',
    count: {
      4: 1,
      5: 1,
      6: 1,
      7: 1,
      8: 1,
      9: 1,
      10: 1,
      11: 1,
    },
    imageBackside: '/images/event.png',
    alt: 'BeFriends',
    on: [],
    action: 'BeFriends',
    type: 'notpanic',
    description: {},
  },
  {
    title: 'BlindDate',
    imagePath: '/images/BlindDate.png',
    count: {
      4: 1,
      5: 1,
      6: 1,
      7: 1,
      8: 1,
      9: 1,
      10: 1,
      11: 1,
    },
    imageBackside: '/images/event.png',
    alt: 'BlindDate',
    on: [],
    action: 'BlindDate',
    type: 'notpanic',
    description: {},
  },
  {
    title: 'Ooops',
    imagePath: '/images/Ooops.png',
    count: {
      4: 1,
      5: 1,
      6: 1,
      7: 1,
      8: 1,
      9: 1,
      10: 1,
      11: 1,
    },
    imageBackside: '/images/event.png',
    alt: 'Ooops',
    on: [],
    action: 'Ooops',
    type: 'notpanic',
    description: {},
  },
  {
    title: 'BetweenUs',
    imagePath: '/images/BetweenUs.png',
    count: {
      4: 1,
      5: 1,
      6: 1,
      7: 1,
      8: 1,
      9: 1,
      10: 1,
      11: 1,
    },
    imageBackside: '/images/event.png',
    alt: 'BetweenUs',
    on: [],
    action: 'BetweenUs',
    type: 'notpanic',
    description: {},
  },
]
/* const CardTypes = [
  'TheThing',
  'Infected',
  'FlameThrower',
  'Analysis',
  'Axe',
  'Suspicious',
  'Whiskey',
  'Resolute',
  'WatchYourBack',
  'ChangePlaces',
  'YoudBetterRun',
  'Seduction',
  'Scary',
  'ImComfortable',
  'NoThanks',
  'Missed',
  'NoBarbecue',
  'Quarantine',
  'BarredDoor', //19
  'RottenRopes', //старые веревки
  'Revelations', //время признаний
  'OneTwo',
  'ThreeFour',
  'SoThisIstheParty',
  'GoAway',
  'Forgetfull',
  'RoundandRound',
  'BeFriends',
  'BlindDate',
  'Ooops',
  'BetweenUs',
]

function zzz() {
  const zzz = []
  CardTypes.forEach((c) => {
    zzz.push({
      title: c,
      imagePath: '/images/' + c + '.png',
      count: { 4: 1, 5: 1, 6: 1, 7: 1, 8: 1, 9: 1, 10: 1, 11: 1 },
      imageBackside: '/images/event.png',
      alt: c,
      on: [],
      action: c,
      type: 'notpanic',
      description: {},
    })
  })
  console.log(zzz)
}
zzz()
*/
function initializeDeck() {
  const deck = []
  Cards.forEach((c) => {
    for (let i = 0; i < c.count; i++) {
      deck.push({
        id: 0,
        title: c.title,
        on: c.on,
        passive: c.passive,
        type: c.type,
        image: c.image,
        description: c.description,
      })
    }
  })

  return deck.map((c, idx) => ({ ...c, id: idx }))
}
